# Generated by Django 4.2.3 on 2023-07-19 19:32

import dishes.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Soup",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=50)),
                ("description", models.TextField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=6)),
                ("slug", models.SlugField(blank=True, unique=True)),
                ("is_gluten_free", models.BooleanField(blank=True, default=False, null=True)),
                ("is_keto", models.BooleanField(blank=True, default=False, null=True)),
                ("is_low_carb", models.BooleanField(blank=True, default=False, null=True)),
                ("is_vegetarian", models.BooleanField(blank=True, default=False, null=True)),
            ],
            options={
                "verbose_name": "Soup",
                "verbose_name_plural": "Soups",
            },
        ),
        migrations.CreateModel(
            name="Picture",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("image", models.FileField(upload_to="images/", validators=[dishes.validators.validate_file_type])),
                (
                    "soup",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="soup_image", to="dishes.soup"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
