# Generated by Django 4.2.3 on 2023-07-22 09:27

import dishes.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Appetizer",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=50)),
                ("description", models.TextField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=6)),
                ("slug", models.SlugField(blank=True, unique=True)),
                ("image", models.FileField(upload_to="images/", validators=[dishes.validators.validate_file_type])),
                ("is_vegetarian", models.BooleanField(blank=True, default=None, null=True)),
                ("is_gluten_free", models.BooleanField(blank=True, default=None, null=True)),
                ("is_low_carb", models.BooleanField(blank=True, default=None, null=True)),
                ("is_keto", models.BooleanField(blank=True, default=None, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Appetizer",
                "verbose_name_plural": "Appetizers",
            },
        ),
        migrations.CreateModel(
            name="MainDish",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=50)),
                ("description", models.TextField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=6)),
                ("slug", models.SlugField(blank=True, unique=True)),
                ("image", models.FileField(upload_to="images/", validators=[dishes.validators.validate_file_type])),
                ("is_vegetarian", models.BooleanField(blank=True, default=None, null=True)),
                ("is_gluten_free", models.BooleanField(blank=True, default=None, null=True)),
                ("is_low_carb", models.BooleanField(blank=True, default=None, null=True)),
                ("is_keto", models.BooleanField(blank=True, default=None, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Main dish",
                "verbose_name_plural": "Main dishes",
            },
        ),
        migrations.CreateModel(
            name="SideDish",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=50)),
                ("description", models.TextField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=6)),
                ("slug", models.SlugField(blank=True, unique=True)),
                ("image", models.FileField(upload_to="images/", validators=[dishes.validators.validate_file_type])),
                ("is_vegetarian", models.BooleanField(blank=True, default=None, null=True)),
                ("is_gluten_free", models.BooleanField(blank=True, default=None, null=True)),
                ("is_low_carb", models.BooleanField(blank=True, default=None, null=True)),
                ("is_keto", models.BooleanField(blank=True, default=None, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Side dish",
                "verbose_name_plural": "Side dishes",
            },
        ),
        migrations.CreateModel(
            name="Soup",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=50)),
                ("description", models.TextField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=6)),
                ("slug", models.SlugField(blank=True, unique=True)),
                ("image", models.FileField(upload_to="images/", validators=[dishes.validators.validate_file_type])),
                ("is_vegetarian", models.BooleanField(blank=True, default=None, null=True)),
                ("is_gluten_free", models.BooleanField(blank=True, default=None, null=True)),
                ("is_low_carb", models.BooleanField(blank=True, default=None, null=True)),
                ("is_keto", models.BooleanField(blank=True, default=None, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Soup",
                "verbose_name_plural": "Soups",
            },
        ),
    ]
